name: data_viz_workshop
channels:
    - conda-forge
dependencies: 
    - python=3.8
    - bokeh=2.3.3
    - ffmpeg=4.3.1
    - jupyterlab=3.3.0
    - matplotlib=3.5.1
    - numpy=1.22.3
    - pandas=1.4.1
    - seaborn=0.11.2
    - shapely=1.7.1
    - pyviz::geoviews-core=1.9.1
    - pyviz::geoviews=1.9.1
    - pyviz::holoviews=1.14.5
    - pyviz::hvplot=0.7.3
    - pyviz::panel=0.12.1
