name: data_viz_workshop
channels:
    - conda-forge
dependencies:
    - python=3.12
    - bokeh=3.4.1
    - ffmpeg
    - geopandas=0.14.4
    - jupyterlab>=4.1.8
    - matplotlib=3.8.4
    - numpy=1.26.4
    - pandas=2.2.2
    - seaborn=0.13.2
    - shapely=2.0.4
    - pyviz::geoviews-core=1.12.0
    - pyviz::geoviews=1.12.0
    - pyviz::holoviews=1.18.3
    - pyviz::hvplot=0.9.2
    - pyviz::panel=1.4.2
