name: data_viz_workshop
channels:
    - conda-forge
dependencies:
    - python=3.10
    - bokeh=2.4.3
    - ffmpeg
    - geopandas=0.12.2
    - jupyterlab>=3.5.2
    - matplotlib=3.7.1
    - numpy=1.23.5
    - pandas=2.0.0
    - seaborn=0.11.2
    - shapely=1.8.5
    - pyviz::geoviews-core=1.9.6
    - pyviz::geoviews=1.9.6
    - pyviz::holoviews=1.15.4
    - pyviz::hvplot=0.8.3
    - pyviz::panel=0.14.4
